export const seedThreats = [
  {
    title: "Cobalt Strike Beacon C2 Campaign",
    description:
      "Active Cobalt Strike command-and-control infrastructure delivering staged payloads against financial sector endpoints. Multiple beacons observed with custom malleable profiles.",
    severity: "critical",
    category: "C2",
    source: "Cyborg TI Feed",
    confidence: 94,
    status: "active",
    tags: ["cobalt-strike", "c2", "finance", "beacon"],
    mitreTactics: ["Command and Control", "Defense Evasion", "Execution"],
  },
  {
    title: "Phishing Kit: Invoice-themed Credential Harvest",
    description:
      "Large-scale phishing campaign using invoice-themed lures and clone Microsoft 365 login pages. Harvested credentials are exfiltrated to bulletproof hosting.",
    severity: "high",
    category: "Phishing",
    source: "SOC Analyst",
    confidence: 88,
    status: "active",
    tags: ["phishing", "credential-theft", "o365", "invoice"],
    mitreTactics: ["Initial Access", "Credential Access"],
  },
  {
    title: "Ransomware Staging: LockBit Affiliate TTPs",
    description:
      "Pre-ransomware activity including RDP brute force, credential dumping, and lateral movement consistent with LockBit affiliate playbooks.",
    severity: "critical",
    category: "Ransomware",
    source: "Partner ISACs",
    confidence: 91,
    status: "monitoring",
    tags: ["lockbit", "ransomware", "rdp", "lateral-movement"],
    mitreTactics: ["Initial Access", "Lateral Movement", "Impact"],
  },
  {
    title: "Malicious npm Package Supply Chain",
    description:
      "Trojanized npm packages impersonating popular utilities. Packages drop a reverse shell and harvest environment secrets from CI runners.",
    severity: "high",
    category: "Supply Chain",
    source: "Open Source Intel",
    confidence: 82,
    status: "active",
    tags: ["npm", "supply-chain", "devtools", "secrets"],
    mitreTactics: ["Initial Access", "Collection", "Command and Control"],
  },
  {
    title: "Botnet Scanning Wave — SSH/Telnet",
    description:
      "Internet-wide scanning wave targeting SSH and Telnet with credential stuffing. Linked to Mirai variant infrastructure.",
    severity: "medium",
    category: "Botnet",
    source: "Honeypot Network",
    confidence: 76,
    status: "active",
    tags: ["mirai", "ssh", "scanning", "iot"],
    mitreTactics: ["Discovery", "Initial Access"],
  },
  {
    title: "Business Email Compromise — Vendor Impersonation",
    description:
      "BEC campaign spoofing finance vendors and requesting urgent wire transfers. Domain lookalikes registered within the last 14 days.",
    severity: "high",
    category: "BEC",
    source: "Email Gateway",
    confidence: 85,
    status: "monitoring",
    tags: ["bec", "spoofing", "finance", "wire-fraud"],
    mitreTactics: ["Initial Access", "Social Engineering"],
  },
];

export const seedIndicators = [
  {
    type: "ip",
    value: "185.220.101.45",
    severity: "critical",
    confidence: 96,
    tags: ["tor-exit", "c2", "cobalt-strike"],
    description: "Known Cobalt Strike C2 node observed in multiple campaigns.",
    source: "Cyborg TI Feed",
    status: "active",
  },
  {
    type: "ip",
    value: "45.33.32.156",
    severity: "high",
    confidence: 84,
    tags: ["scanning", "ssh-bruteforce"],
    description: "Aggressive SSH brute force source from Linode range.",
    source: "Honeypot Network",
    status: "active",
  },
  {
    type: "domain",
    value: "secure-login-m365[.]online",
    severity: "high",
    confidence: 90,
    tags: ["phishing", "o365", "credential-theft"],
    description: "Phishing domain cloning Microsoft 365 authentication portal.",
    source: "SOC Analyst",
    status: "active",
  },
  {
    type: "domain",
    value: "invoice-portal-secure[.]com",
    severity: "high",
    confidence: 87,
    tags: ["phishing", "invoice"],
    description: "Invoice-themed phishing landing page domain.",
    source: "Email Gateway",
    status: "active",
  },
  {
    type: "url",
    value: "https://cdn-updates-check[.]net/payload/stage2.bin",
    severity: "critical",
    confidence: 93,
    tags: ["malware-delivery", "stage2"],
    description: "Second-stage payload delivery URL used by LockBit-related activity.",
    source: "Partner ISACs",
    status: "active",
  },
  {
    type: "hash",
    value: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    severity: "medium",
    confidence: 70,
    tags: ["sample", "placeholder-hash"],
    description: "SHA-256 hash associated with trojanized npm installer dropper (example).",
    source: "Open Source Intel",
    status: "monitoring",
  },
  {
    type: "hash",
    value: "44d88612fea8a8f36de82e1278abb02f",
    severity: "high",
    confidence: 88,
    tags: ["md5", "ransomware"],
    description: "MD5 of ransomware loader recovered from infected workstation.",
    source: "IR Team",
    status: "active",
  },
  {
    type: "email",
    value: "payments@vendor-support-secure.com",
    severity: "high",
    confidence: 81,
    tags: ["bec", "spoof"],
    description: "Sender used in vendor impersonation BEC campaign.",
    source: "Email Gateway",
    status: "active",
  },
  {
    type: "ip",
    value: "103.27.202.88",
    severity: "medium",
    confidence: 72,
    tags: ["proxy", "suspicious"],
    description: "Open proxy frequently used for phishing kit management panels.",
    source: "Cyborg TI Feed",
    status: "active",
  },
  {
    type: "filename",
    value: "Invoice_Q1_Payment.exe",
    severity: "high",
    confidence: 86,
    tags: ["lure", "exe", "malware"],
    description: "Malicious invoice lure executable delivered via email attachment.",
    source: "SOC Analyst",
    status: "active",
  },
];

export const seedIpReputations = [
  {
    ip: "185.220.101.45",
    score: 97,
    riskLevel: "critical",
    country: "DE",
    asn: "AS60729",
    isp: "ZWIEBELFREUNDE",
    abuseReports: 214,
    categories: ["tor", "c2", "malware"],
    notes: "High-confidence malicious C2 / Tor exit activity.",
  },
  {
    ip: "45.33.32.156",
    score: 78,
    riskLevel: "high",
    country: "US",
    asn: "AS63949",
    isp: "Akamai Connected Cloud",
    abuseReports: 63,
    categories: ["bruteforce", "scanning"],
    notes: "Persistent SSH authentication attacks against enterprise perimeter.",
  },
  {
    ip: "8.8.8.8",
    score: 2,
    riskLevel: "clean",
    country: "US",
    asn: "AS15169",
    isp: "Google LLC",
    abuseReports: 0,
    categories: ["dns", "public-resolver"],
    notes: "Public DNS resolver. No malicious activity attributed.",
  },
  {
    ip: "1.1.1.1",
    score: 3,
    riskLevel: "clean",
    country: "AU",
    asn: "AS13335",
    isp: "Cloudflare, Inc.",
    abuseReports: 0,
    categories: ["dns", "public-resolver"],
    notes: "Public DNS resolver. Benign reputation.",
  },
  {
    ip: "103.27.202.88",
    score: 61,
    riskLevel: "medium",
    country: "HK",
    asn: "AS133199",
    isp: "SonderCloud Limited",
    abuseReports: 27,
    categories: ["proxy", "phishing-infra"],
    notes: "Associated with phishing kit panels and open proxy services.",
  },
  {
    ip: "91.219.236.177",
    score: 89,
    riskLevel: "high",
    country: "NL",
    asn: "AS48693",
    isp: "RUVDS.com",
    abuseReports: 118,
    categories: ["malware", "c2"],
    notes: "Hosting multiple malicious payloads and C2 listeners.",
  },
  {
    ip: "192.168.10.55",
    score: 12,
    riskLevel: "low",
    country: "Internal",
    asn: "PRIVATE",
    isp: "Corporate LAN",
    abuseReports: 0,
    categories: ["internal"],
    notes: "RFC1918 private address. Use contextual host inventory for risk.",
  },
];
